name = "jhm4_site"
version = "1.0.0"
target = "erlang"

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
lustre = ">= 5.7.0 and < 6.0.0"
mork = ">= 1.12.0 and < 2.0.0"
mork_to_lustre = ">= 0.2.0 and < 1.0.0"
simplifile = ">= 2.3.0 and < 3.0.0"
